### ISSUE TITLE
Check already latest version

### ISSUE THREAD

**Issue by AhmerAfzal1** [systembugtj/AutoUpdate#1]
First thanks for great library, how I can check via `Toast` whether app is running already with latest version or not.

**Comment by systembugtj** [comment]
Currently, the design is to only show dialog when need to update. So what you expect is to allow do something after checking version?

**Comment by AhmerAfzal1** [comment]
I want to do that the user can find out that there is no new update yet. I introduced a button to perform this task. If this feature is not available, the user will feel that he is pressing the button itself. That's why it is important to tell the user that the new update is not available.

**Comment by systembugtj** [comment]
How about a checkForCustomNotice() may help you.

And you can handle it on your side. Something like below.

handleUpdateNotice( UpdateDescription description)

**Comment by systembugtj** [comment]
Check this PR https://github.com/systembugtj/AutoUpdate/pull/2

**Comment by AhmerAfzal1** [comment]
`showCustomNotice` can perform this `description.versionCode > versionCode` if newer version available than show `Dialog` to Download else show `Toast` No new version available to download.

`showCustomNotice` won't do what actually need

**Comment by AhmerAfzal1** [comment]
I try but fail
```
UpdateDescription description;
int versionCode = 0;
.
.
.
try {
    versionCode = this.getPackageManager().getPackageInfo(this.getPackageName(), 0).versionCode;
      }
catch (PackageManager.NameNotFoundException e)
        {  }
.
.
.
if (description.versionCode > versionCode)
                {
                    UpdateChecker.checkForDialog(SettingsActivity.this, APP_UPDATE_SERVER_URL, true, true);
                }
                else
                    {
                        Toast.makeText(SettingsActivity.this, "No new version available", Toast.LENGTH_LONG).show();
                    }
```

**Comment by systembugtj** [comment]
Please check the sample how it works for the checkForCustomNotice. 
Your activity should implement UpdateNotice interface and, when showCustomNotice be called, you have the UpdateDescription, then you can decide what to do next.

**Comment by AhmerAfzal1** [comment]
Dear! 
`checkForCustomNotice` can create a `UpdateDialog` for what we need to show, but user need these 
```
UpdateChecker.checkForDialog(MainActivity.this, APP_UPDATE_SERVER_URL, false, true);
UpdateChecker.checkForDialog(MainActivity.this, APP_UPDATE_SERVER_URL, true, true);
UpdateChecker.checkForNotification(MainActivity.this, APP_UPDATE_SERVER_URL, false, false);
UpdateChecker.checkForNotification(MainActivity.this, APP_UPDATE_SERVER_URL, true, true);
```
standard method well defined to check app update in these methods user need if newer version available using these methods what user has choosed to implement it, else it shows a `Toast` that "Currently there is no new version available to download". This simple method need to develop. 

Get it done in any way here
```
else {
       Log.i(TAG, mContext.getString(R.string.app_no_new_update));
       Toast.makeText(UpdateChecker.this, "Currently there is no new version available to download", Toast.LENGTH_LONG).show();
}
```

**Comment by systembugtj** [comment]
The goal of checkForCustomNotice is to control the UI by your side.

You can use notification or dialog to do the rest work.
